variables:

  # app version, changing version will auto deploy the app to current version
  imageAppVersion: "2.2.20"

  #app buil image
  imageRepository: "registry.nise.gov.bd/nise3-organization-management-api-service"
